
zuul:
  routes:
#    auth:
#      path: /api-uaa/**
#      service-id: uaa-server
#      strip-prefix: true
#      custom-sensitive-headers: true
#    auth-login-page:
#      path: /login.html
#      service-id: uaa-server
#      strip-prefix: true
#      custom-sensitive-headers: true
#    auth-login-process:
#      path: /user/login
#      service-id: uaa-server
#      strip-prefix: true
#      custom-sensitive-headers: true
#    auth-login-token:
#      path: /oauth/token
#      service-id: uaa-server
#      strip-prefix: true
#      custom-sensitive-headers: true
#    auth-login-authorize:
#      path: /oauth/authorize
#      service-id: uaa-server
#      strip-prefix: true
#      custom-sensitive-headers: true
#    auth-check-process:
#      path: /oauth/check_token
#      service-id: uaa-server
#      strip-prefix: true
#      custom-sensitive-headers: true
    user:
      path: /api-sys/**
      service-id: yida-sys
      strip-prefix: true
      custom-sensitive-headers: true
    file:
      path: /api-file/**
      service-id: file-center
      strip-prefix: true
    log:
      path: /api-log/**
      service-id: log-center
      strip-prefix: true
    generator:
      path: /api-generator/**
      service-id: code-generator
      strip-prefix: true
    member:
      path: /api-member/**
      service-id: mapper-center
      strip-prefix: true
      custom-sensitive-headers: true
    goods:
      path: /api-goods/**
      service-id: goods-center
      strip-prefix: true
      custom-sensitive-headers: true
    order:
      path: /api-order/**
      service-id: order-center
      strip-prefix: true
      custom-sensitive-headers: true
    marking:
      path: /api-marking/**
      service-id: marking-center
      strip-prefix: true
      custom-sensitive-headers: true
    cms:
      path: /api-cms/**
      service-id: cms-center
      strip-prefix: true
      custom-sensitive-headers: true
    ssl-hostname-validation-enabled: false